# Display management
bindd = SUPER CTRL, P, Hyprmon, exec, omarchy-launch-or-focus-tui hyprmon

# Power profile
bindd = ,XF86Launch4, Toggle power profile, exec, asusctl profile next && notify-send "$(asusctl profile get | head -n 1)"

# TODO
bind = ,XF86Launch1, exec, notify-send "pressed"
bind = ,XF86Launch3, exec,  notify-send "pressed"
