#!/bin/bash

case "$1" in
  catppuccin)
  COLOUR='8A2BE2'
  ;;
  catppuccin-latte)
  COLOUR='CC8899'
  ;;
  ethereal)
  COLOUR='192F7E'
  ;;
  everforest)
  COLOUR='36454F'
  ;;
  flexoki-light)
  COLOUR='F5F5DC'
  ;;
  gruvbox)
  COLOUR='06402B'
  ;;
  hackerman)
  COLOUR='00008B'
  ;;
  kanagawa)
  COLOUR='ADD8E6'
  ;;
  matte-black)
  COLOUR='FF5C00'
  ;;
  nord)
  COLOUR='ADD8E6'
  ;;
  osaka-jade)
  COLOUR='2E6F40'
  ;;
  ristretto)
  COLOUR='996515'
  ;;
  rose-pine)
  COLOUR='FF8DA1'
  ;;
  tokyo-night)
  COLOUR='0000FF'
  ;;
esac

if [ -n "$COLOUR" ]; then
  asusctl aura effect static --colour "$COLOUR"
fi
